// Right-panel view for a selected image node: the image large, a debounced
// feedback textarea, provenance, and delete (backend enforces the deletion
// rules; 409s are surfaced as a toast).
//
// Extension point: the annotation overlay (like/dislike/note rectangles)
// draws on top of the <img> below, next slice.
import { useEffect, useRef, useState } from "react";
import { useDeleteImage, usePatchImage } from "../api/queries";
import { useEditorStore } from "../store";
import { Button, Textarea } from "../components/ui";
import type { ConceptNode, ImageNode } from "../api/types";

export function ImagePanel({
  image,
  producingConcept,
}: {
  image: ImageNode;
  producingConcept: ConceptNode | undefined;
}) {
  const [feedback, setFeedback] = useState(image.feedback);
  const patchImage = usePatchImage();
  const deleteImage = useDeleteImage();
  const selectNode = useEditorStore((s) => s.selectNode);
  const showToast = useEditorStore((s) => s.showToast);

  useEffect(() => {
    setFeedback(image.feedback);
  }, [image.id]);

  const saveTimer = useRef<ReturnType<typeof setTimeout> | null>(null);
  const scheduleSave = (next: string) => {
    if (saveTimer.current) clearTimeout(saveTimer.current);
    saveTimer.current = setTimeout(() => {
      patchImage.mutate(
        { id: image.id, body: { feedback: next } },
        { onError: (err) => showToast(err.message) },
      );
    }, 500);
  };

  const handleDelete = () => {
    deleteImage.mutate(image.id, {
      onSuccess: () => selectNode(null),
      onError: (err) => showToast(err.message),
    });
  };

  const provenance =
    image.source === "uploaded"
      ? "Uploaded"
      : `Generated by ${producingConcept?.title || "an unknown concept"}`;

  return (
    <div className="flex h-full min-h-0 flex-col gap-3 p-4">
      <div className="relative overflow-hidden rounded-md border border-gray-200">
        <img src={image.url} alt="" className="block w-full" />
        {/* Extension point: annotation overlay mounts here. */}
        <div className="pointer-events-none absolute inset-0" data-annotation-overlay-slot="" />
      </div>

      <p className="text-xs text-gray-500">{provenance}</p>

      <div>
        <label className="mb-1 block text-xs font-semibold uppercase tracking-wide text-gray-500">
          Feedback
        </label>
        <Textarea
          rows={4}
          placeholder="What works, what doesn't..."
          value={feedback}
          onChange={(e) => {
            setFeedback(e.target.value);
            scheduleSave(e.target.value);
          }}
        />
      </div>

      <Button variant="danger" className="self-start" onClick={handleDelete} disabled={deleteImage.isPending}>
        Delete
      </Button>
    </div>
  );
}
